export const sliderItems = [
  {
    id: 1,
    img: "/images/skincare-header03.jpg",
    title: "",
    desc: "",
  },
  {
    id: 2,
    img: "/images/home-header.jpg",
    title: "",
    desc: "",
  },
  {
    id: 3,
    img: "/images/gardening-header.jpg",
    title: "",
    desc: "",
  },
];

export const category = [
  {
    id: 1,
    img: "/images/home-header.jpg",
    title: "Home",
  },
  {
    id: 2,
    img: "/images/tote-header.jpg",
    title: "Tote-bag",
  },
  {
    id: 3,
    img: "/images/makeup-header.jpg",
    title: "Makeup",
  },
  {
    id: 4,
    img: "/images/fashion-header.jpg",
    title: "Fashion",
  },
  {
    id: 5,
    img: "/images/gardening-header02.jpg",
    title: "Gardening",
  },
  {
    id: 6,
    img: "/images/skincare-header01.jpg",
    title: "Hygiene",
  },
];
export const dataList = [
  {
    id: 1,
    img1: "/images/soaptype101.jpg",
    img2: "/images/soaptype102.jpg",
    title: "Organic Moisturizing Soap",
    desc: "Organic Moisturizing Soap produced by Soaps from Heaven",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 2,
    img1: "/images/netype02.jpg",
    img2: "/images/netype2.jpg",
    title: "Mesh bag - type A",
    desc: "Fine-grained net/mesh bag type A",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 3,
    img1: "/images/bathcol01.jpg",
    img2: "/images/bathcol02.jpg",
    title: "Bathing items set A",
    desc: "Collection of bathing items",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 4,
    img1: "/images/makeup-pad01.jpg",
    img2: "/images/makeup-pad02.jpg",
    title: "Makeup Pads",
    desc: "Makeup Pads",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 5,
    img1: "/images/basket01.jpg",
    img2: "/images/basket02.jpg",
    title: "Shopping Basket",
    desc: "Wooden shopping basket",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 6,
    img1: "/images/cutleryset01.jpg",
    img2: "/images/cutleryset02.jpg",
    title: "Bamboo cutlery set",
    desc: "Bamboo cutlery set",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Home",
  },
  {
    id: 7,
    img1: "/images/cottonmask01.jpg",
    img2: "/images/cottonmask02.jpg",
    title: "Cotton Mask",
    desc: "Cotton mask",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Fashion",
  },
  {
    id: 8,
    img1: "/images/eye-serum01.jpg",
    img2: "/images/eye-serum02.jpg",
    title: "Organic Eye Serum",
    desc: "Organic Eye Serum",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 9,
    img1: "/images/mesh-bag01.jpg",
    img2: "/images/mesh-bag02.jpg",
    title: "Mesh Bag - Type C",
    desc: "Mesh Bag - Type C",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 10,
    img1: "/images/shirt01.jpg",
    img2: "/images/shirt02.jpg",
    title: "Sustainable White Shirt",
    desc: "Sustainable White Shirt",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Fashion",
  },
  {
    id: 11,
    img1: "/images/cotton-swab01.jpg",
    img2: "/images/cotton-swab02.jpg",
    title: "Bamboo Cotton Swabs",
    desc: "Bamboo Cotton Swabs",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 12,
    img1: "/images/toothbrush01.jpg",
    img2: "/images/toothbrush02.jpg",
    title: "Bamboo Toothbrush",
    desc: "Bamboo Toothbrush",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 13,
    img1: "/images/veganshampoo01.jpg",
    img2: "/images/veganshampoo02.jpg",
    title: "Vegan Shampoo",
    desc: "Vegan Shampoo by Nature Ward",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 14,
    img1: "/images/lipstick01.jpg",
    img2: "/images/lipstick02.jpg",
    title: "Organic Lipstick",
    desc: "Organic Lipstick",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 15,
    img1: "/images/cream-powder01.jpg",
    img2: "/images/cream-powder02.jpg",
    title: "Organic Cream Powder",
    desc: "Organic Cream Powder",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 16,
    img1: "/images/bathcoltypeb01.jpg",
    img2: "/images/bathcoltypeb02.jpg",
    title: "Bathing items set B",
    desc: "Collection of bathing items",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 17,
    img1: "/images/mesh01.jpg",
    img2: "/images/mesh02.jpg",
    title: "Mesh bag type B",
    desc: "Fine-grained net/mesh bag type B",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 18,
    img1: "/images/sweater01.jpg",
    img2: "/images/sweater02.jpg",
    title: "Sustainable Sweater",
    desc: "Sustainable Sweater",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Fashion",
  },
  {
    id: 19,
    img1: "/images/wooden-bottle01.jpg",
    img2: "/images/wooden-bottle02.jpg",
    title: "Bamboo Bottle",
    desc: "Bamboo Bottle",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Home",
  },
  {
    id: 20,
    img1: "/images/liquid-lipstick01.png",
    img2: "/images/liquid-lipstick02.png",
    title: "Organic Liquid Lipstick",
    desc: "Organic Liquid Lipstick",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 21,
    img1: "/images/jaderoller01.jpg",
    img2: "/images/jaderoller02.jpg",
    img3: "/images/jaderoller03.jpg",
    img4: "/images/jaderoller04.jpg",
    title: "Jade Roller and Gua Sha",
    desc: "Jade Roller and Gua Sha",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 22,
    img1: "/images/eyeshadow01.png",
    img2: "/images/eyeshadow02.jpg",
    title: "Organic Eyeshadow",
    desc: "Organic Eyeshadow",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 23,
    img1: "/images/metal-straw01.jpg",
    img2: "/images/metal-straw02.jpg",
    img3: "/images/metal-straw03.jpg",
    title: "Metal Straw",
    desc: "Metal Straw",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Home",
  },
  {
    id: 24,
    img1: "/images/pridebag01.jpg",
    img2: "/images/pridebag02.jpg",
    title: "Pride Tote bag",
    desc: "Pride Tote bag",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 25,
    img1: "/images/moisturizer01.jpg",
    img2: "/images/moisturizer02.jpg",
    title: "Organic Moisturizer",
    desc: "Organic Moisturizer",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 26,
    img1: "/images/golde-straw01.jpg",
    img2: "/images/golde-straw02.jpg",
    title: "Metal Straw - Golden",
    desc: "Metal Straw - Golden",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Home",
  },
  {
    id: 27,
    img1: "/images/jeans01.jpg",
    img2: "/images/jeans02.jpg",
    title: "Sustainable Jeans",
    desc: "Sustainable Jeans",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Fashion",
  },
  {
    id: 28,
    img1: "/images/soaptype201.jpg",
    img2: "/images/soaptype202.jpg",
    title: "Organic Soap",
    desc: "Organic Soap",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 29,
    img1: "/images/clothbag01.jpg",
    img2: "/images/clothbag02.jpg",
    title: "Minimalistic tote bag",
    desc: "Minimalistic tote bag",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 30,
    img1: "/images/face-mist01.jpg",
    img2: "/images/face-mist02.jpg",
    title: "Organic Face Mist",
    desc: "Organic Face Mist",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Hygiene",
  },
  {
    id: 31,
    img1: "/images/net01.jpg",
    img2: "/images/net02.jpg",
    img3: "/images/net03.jpg",
    title: "Net Bag",
    desc: "Net Bag",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Tote-bag",
  },
  {
    id: 32,
    img1: "/images/tshirt01.jpg",
    img2: "/images/tshirt02.jpg",
    title: "Sustainable T-shirt",
    desc: "Sustainable T-shirt",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Fashion",
  },
  {
    id: 33,
    img1: "/images/bb-cream01.jpg",
    img2: "/images/bb-cream02.jpg",
    title: "Organic BB Cream",
    desc: "Organic BB Cream",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Makeup",
  },
  {
    id: 34,
    img1: "/images/bambo-straw01.jpg",
    img2: "/images/bambo-straw02.jpg",
    title: "Bamboo Straw",
    desc: "Bamboo Straw",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Home",
  },
  {
    id: 35,
    img1: "/images/strawberry01.jpg",
    img2: "/images/strawberry02.jpg",
    title: "Strawberry Seeds",
    desc: "Strawberry Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 36,
    img1: "/images/watermelon01.jpg",
    img2: "/images/watermelon02.jpg",
    title: "Watermelon Seeds",
    desc: "Watermelon Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 37,
    img1: "/images/sunflower01.jpg",
    img2: "/images/sunflower02.jpg",
    title: "Sunflower Seeds",
    desc: "Sunflower Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 38,
    img1: "/images/mentha01.jpg",
    img2: "/images/mentha02.jpg",
    title: "Mentha Seeds",
    desc: "Mentha Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 39,
    img1: "/images/marguerite01.jpg",
    img2: "/images/marguerite02.jpg",
    title: "Marguerite Seeds",
    desc: "Marguerite Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 40,
    img1: "/images/carrot01.jpg",
    img2: "/images/carrot02.jpg",
    title: "Carrot Seeds",
    desc: "Carrot Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 41,
    img1: "/images/parsley01.jpg",
    img2: "/images/parsley02.jpg",
    title: "Parsley Seeds",
    desc: "Parsley Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 42,
    img1: "/images/blackberry01.jpg",
    img2: "/images/blackberry02.jpg",
    title: "Blackberry Seeds",
    desc: "Blackberry Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 43,
    img1: "/images/bluemink01.jpg",
    img2: "/images/bluemink02.jpg",
    title: "Bluemink Seeds",
    desc: "Bluemink Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
  {
    id: 44,
    img1: "/images/eaggplant01.jpg",
    img2: "/images/eaggplant02.png",
    title: "Eggplant Seeds",
    desc: "Eggplant Seeds",
    isNew: true,
    oldPrice: 30,
    price: 13,
    cat: "Gardening",
  },
];
